---
title: "Lab 8 - Linear Regression in R"
author: "Rachel Green"
date: "November 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

salmon <- read_csv("salmon.csv")

```

```{r}

salmon_model <- lm(salmon_fresh ~ year, salmon)

salmon_model


par(mfrow = c(2,2))
plot(salmon_model)

summary(salmon_model)
```
Imports(tons) = -14982940 + 7550(year)


```{r}

salmon_final_graph <- ggplot(salmon, aes(x = year, y = salmon_fresh)) +
geom_point() +
geom_smooth(method = lm, se = TRUE, size = 0.5, color = "gray20") +
theme_bw() +
scale_x_continuous(expand = c(0,0), limits = c(1990, 2017)) +
labs(x = "Year", y = "U.S. Annual Fresh Salmon Imports\n(1,000 pounds)")
salmon_final_graph


```

```{r}

new_years <- data.frame(year = c(2022, 2024, 2026, 2028))


future_predict <- predict(salmon_model, newdata = new_years, interval = "confidence")
future_predict

predictions <- data.frame(new_years, future_predict)
predictions

salmon_correlation <- cor(salmon$salmon_fresh, salmon$year)
salmon_correlation

```

